#!/usr/bin/env ruby
require 'date'
	true

def exit_with_usage_instructions
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers.rb [Name] [MM/DD Birthday]
EOS
  exit
end


exit_with_usage_instructions() if ARGV.empty?

if ARGV.length == 1
  original_name = ARGV[0]
  birthday = ""
else
  original_name = ARGV[0]
  birthday = ARGV[1]
  begin
    Date.parse(birthday)
  rescue
    exit_with_help_message
  end
end



original_name = ARGV[0]
birthday = ARGV[1]
cheerable_name = original_name.upcase.gsub(/[^A-Z]/, "")

exit_with_usage_instructions if cheerable_name.empty?

cheerable_name.each_char do |char|
  article = "n" if "HALFNORSEMIX".include? char
  puts "Give me a#{article}... #{char}"
end
puts "#{original_name}'s just GRAND!"
puts ""
if birthday == ""
	puts 'I would wish you a Happy Birthday, if I knew when that was!'
else
	days_until = Date.parse(birthday) - Date.today
  if days_until == 0
    puts "Awesome!  Your birthday is today! Happy Birthday!"
  elsif days_until == 1
    puts "Awesome!  Your birthday is in #{days_until} day! Happy Birthday in advance!"
  else
    puts "Awesome!  Your birthday is in #{days_until.to_i} days! Happy Birthday in advance!"
  end
end

